### PR TITLE
fix: ensure we always get schema version the same way

### LINKED ISSUE #1143: Enusure schema version in WASM lib and schema version when uploading, match
- I'm not sure exactly what this issue might be but just leaving a note
- We encountered this issue when migrating the playground from prod to dev
- Apparently there was an indexer (shoutbox) that had a different version in its WASM lib, than it had in the DB
 - Meaning `VERSION` in the WASM lib, was different from `schema_version` in `graph_registry_type_ids`
- How did this happen? Not sure yet
- However, we should add some validation when registering these indexers to ensure this doesn't happen and return a 400 or something if it happens

### PR DESCRIPTION
**Pull request by lostman**
Thanks for opening a PR with the Fuel Indexer project, please review the **Checklist** below and ensure you've completed all of the necessary steps to make this PR review as painless as possible.

### Description

Closes #1143.

When creating `WasmIndexExecutor`, we no longer get the schema version through the FFI from the WASM file. Instead, we always get it from the `Manifest` through the `GraphQLSchema` struct.

In addition, when `WasmIndexExecutor` is created, we check that the WASM module version matches the schema file's version.

### Testing steps

CI tests are sufficient.

`build-and-test-examples` already caught an error in an earlier version:
https://github.com/FuelLabs/fuel-indexer/actions/runs/5809617283/job/15748759298

### Changelog

* `WasmIndexExecutor::new` now takes a `schema_version` `String`.
* Check that the WASM version matches the schema version.

### CODE REVIEW

File: packages/fuel-indexer-api-server/src/uses.rs [hunk 1]
```diff
@@ -261,20 +261,21 @@ pub(crate) async fn register_indexer_assets(
...
+                            let schema = GraphQLSchema::new(
+                                String::from_utf8_lossy(&data).to_string(),
+                            );
+
                             match queries::register_indexer_asset(
                                 &mut conn,
                                 &namespace,
                                 &identifier,
-                                data.to_vec(),
+                                schema.to_string().as_bytes().to_vec(),
```
Comment (ra0x3) [inline packages/fuel-indexer-api-server/src/uses.rs]: Can we make this a bit more idiomatic?

```rust
impl From<GraphQLSchema> for Vec<u8> {
  fn from(schema: GraphQLSchema) -> Self {
    // ...
  }
}
```

then 

```rust
&mut conn,
&namespace,
&identifier,
schema.into()
```

File: packages/fuel-indexer-lib/src/graphql/mod.rs [hunk 2]
```diff
@@ -56,7 +56,11 @@ type IndexMetadataEntity @entity {
 
 /// Inject native entities into the GraphQL schema.
 fn inject_native_entities_into_schema(schema: &str) -> String {
-    format!("{}{}", schema, IndexMetadata::schema_fragment())
+    if !schema.contains("type IndexMetadataEntity") {
```
Comment (ra0x3) [inline packages/fuel-indexer-lib/src/graphql/mod.rs:59]: 👌🏽

File: packages/fuel-indexer/src/executor.rs [hunk 3]
```diff
@@ -631,12 +632,18 @@ impl WasmIndexExecutor {
             return Err(IndexerError::MissingHandler);
         }
 
-        // FunctionEnvMut and SotreMut must be scoped because they can't be used
-        // across await
-        let version = {
+        // FunctionEnvMut and SotreMut must be scoped with {} because they can't
```
Comment (ra0x3) [inline packages/fuel-indexer/src/executor.rs]:
```suggestion
        // FunctionEnvMut and StoreMut must be scoped because they can't
```
The term "scoped" implies `{}`

File: packages/fuel-indexer/src/executor.rs [hunk 4]
```diff
@@ -631,12 +632,18 @@ impl WasmIndexExecutor {
...
+        // be used across await
+        {
             let mut env_mut = env.clone().into_mut(&mut store);
             let (data_mut, mut store_mut) = env_mut.data_and_store_mut();
 
+            let schema_version_from_wasm = ffi::get_version(&mut store_mut, &instance)?;
+
+            if schema_version_from_wasm != schema_version {
+                return Err(IndexerError::Unknown(format!("Schema version from WASM {schema_version_from_wasm} does not match schema version {schema_version}")));
```
Comment (ra0x3) [inline packages/fuel-indexer/src/executor.rs:644]: 👌🏽

**Review by ra0x3 — CHANGES_REQUESTED** [review]
@lostman Looks OK. Small pieces of feedback

**Comment by ra0x3** [comment]
@lostman Also, this PR does not include any testing steps

File: packages/fuel-indexer-api-server/src/uses.rs [hunk 5]
```diff
@@ -261,20 +261,21 @@ pub(crate) async fn register_indexer_assets(
                             }
                         }
                         IndexerAssetType::Schema => {
+                            let schema = GraphQLSchema::new(
```
Comment (ra0x3) [inline packages/fuel-indexer-api-server/src/uses.rs]: Sorry I missed this prior @lostman but again here

```rust
let schema = GraphQLSchema::from(&data)
```

With:

```rust
impl From<Vec<u8>> for GraphQLSchema 
```

**Review by ra0x3 — APPROVED** [review]
