### PR TITLE
enhancement, fix (fuel-indexer-macros): Adjustments to `Return` and `ReturnData` receipt handling

### LINKED ISSUE #449: Bug in Receipt::ReturnData handling breaks reference type return values
Hi - I've ran into a bizarre bug where I'm able to successfully index my receipts if the function called returns either nothing or a non-reference type (e.g. `u64`), but things break if the function returns a reference type (e.g. `b256`).

For context, I'm using wasm and I'm just indexing using a basic function that isn't specific to any log format:
```
#[indexer(manifest = "fuel-contracts/indexer/mailbox/mailbox.manifest.yaml")]
mod hello_world_index {

    fn index_block(block_data: BlockData) {
      // In here I'm looping through all the txs & their receipts,
      // looking for certain LogData receipts, and saving them
    }
}
```

And the transaction I'm attempting to index was created with fuels-ts.

### Background

Here's an example of what the receipts look like for a tx of mine that calls a function that returns a `u64` and also logs some data:
```
receipts: [
  Call { id: 0000000000000000000000000000000000000000000000000000000000000000, to: 69ec8b0544b6549354e373e021fc874305176c7b81db6da8d16cded3950d9f9f, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 99970291, param1: 4000556463, param2: 0, pc: 17216, is: 17216 },
  LogData { id: 69ec8b0544b6549354e373e021fc874305176c7b81db6da8d16cded3950d9f9f, ra: 0, rb: 6846832, ptr: 67108626, len: 77, digest: ccbcf7ee5796d9316fd3472b561feb99a51d3d97e82426b75df4a093faedc890, data: [0, 0, 0, 0, 0, 102, 117, 101, 108, 107, 99, 128, 76, 251, 249, 133, 110, 104, 229, 182, 231, 174, 242, 56, 220, 131, 17, 236, 85, 190, 192, 77, 247, 116, 0, 58, 44, 150, 224, 65, 142, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], pc: 25284, is: 17216 },
  Return { id: 69ec8b0544b6549354e373e021fc874305176c7b81db6da8d16cded3950d9f9f, val: 69, pc: 25292, is: 17216 },
  ReturnData { id: 0000000000000000000000000000000000000000000000000000000000000000, ptr: 67108544, len: 160, digest: de5c8876a60211bd60e33fed909e43cc8762a364833eb5c0014a745283045d78, data: [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 69, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 184, 0, 0, 0, 0, 0, 0, 58, 152, 0, 0, 0, 0, 0, 0, 64, 232, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 255, 255, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 245, 98, 243, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 104, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 245, 108, 243, 0, 0, 0, 0, 0, 0, 59, 240], pc: 11496, is: 10344 },
  ScriptResult { result: Success, gas_used: 135105 }], id: 371821733e4c23b30791fb078dd269b58e2481a3ec662a13ee1fc047fce62c5c }
]
```
My contract's ID is `69ec8b0544b6549354e373e021fc874305176c7b81db6da8d16cded3950d9f9f`, and you can see the function returns `69` which is shown in the `Return` receipt because it's a non-reference type. There's still a `ReturnData`, which I believe is from my tx's script because of the contract_id being `000..000`.

And then here's an example of the receipts when my function returns a `b256`:
```
receipts: [
  Call { id: 0000000000000000000000000000000000000000000000000000000000000000, to: c2a3d7758a0a9e65344d05df8d0a320ef95676cd5243192b8a9d3c7b29b18b60, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 99970291, param1: 4000556463, param2: 0, pc: 17216, is: 17216 },
  LogData { id: c2a3d7758a0a9e65344d05df8d0a320ef95676cd5243192b8a9d3c7b29b18b60, ra: 0, rb: 6846832, ptr: 67108626, len: 77, digest: ccbcf7ee5796d9316fd3472b561feb99a51d3d97e82426b75df4a093faedc890, data: [0, 0, 0, 0, 0, 102, 117, 101, 108, 107, 99, 128, 76, 251, 249, 133, 110, 104, 229, 182, 231, 174, 242, 56, 220, 131, 17, 236, 85, 190, 192, 77, 247, 116, 0, 58, 44, 150, 224, 65, 142, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], pc: 25284, is: 17216 },
  ReturnData { id: c2a3d7758a0a9e65344d05df8d0a320ef95676cd5243192b8a9d3c7b29b18b60, ptr: 40600, len: 32, digest: 4bb6ce494b0c83d01f626aaa6a1db74965e23a40e551001ce18df635dad35b1b, data: [111, 243, 110, 67, 158, 34, 203, 158, 167, 116, 216, 194, 39, 75, 63, 28, 68, 59, 83, 155, 237, 211, 102, 207, 178, 168, 81, 1, 6, 25, 54, 12], pc: 25300, is: 17216 },
  ReturnData { id: 0000000000000000000000000000000000000000000000000000000000000000, ptr: 67108320, len: 192, digest: 2a35a3f8767775e3ae7f10cef55d4e29a5c0b31a6247e665861e901b28c88e46, data: [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 245, 98, 243, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 59, 240, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 60, 200, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 60, 64, 0, 0, 0, 0, 0, 0, 53, 152, 0, 0, 0, 0, 0, 0, 58, 152, 111, 243, 110, 67, 158, 34, 203, 158, 167, 116, 216, 194, 39, 75, 63, 28, 68, 59, 83, 155, 237, 211, 102, 207, 178, 168, 81, 1, 6, 25, 54, 12], pc: 11496, is: 10344 },
  ScriptResult { result: Success, gas_used: 151261 }], id: 5249d3c76901e5bd4d748ce8c30c45ebb306879777db6bc6f6439e98c3251b8a }
]
```

Here my contract's id is `c2a3d7758a0a9e65344d05df8d0a320ef95676cd5243192b8a9d3c7b29b18b60`. Note that the return value from my function is now a `ReturnData` when I return the b256 `6ff36e439e22cb9ea774d8c2274b3f1c443b539bedd366cfb2a851010619360c`: `ReturnData { id: c2a3d7758a0a9e65344d05df8d0a320ef95676cd5243192b8a9d3c7b29b18b60, ptr: 40600, len: 32, digest: 4bb6ce494b0c83d01f626aaa6a1db74965e23a40e551001ce18df635dad35b1b, data: [111, 243, 110, 67, 158, 34, 203, 158, 167, 116, 216, 194, 39, 75, 63, 28, 68, 59, 83, 155, 237, 211, 102, 207, 178, 168, 81, 1, 6, 25, 54, 12], pc: 25300, is: 17216 }`. Also note that there is still a ReturnData with the id `000..000` which I assume is from my tx's script.

This results in these logs, which prevents any of my data from being actually written to the db:
```
Jan 05 13:02:07.890  WARN fuel_indexer::ffi: Unknown logged type ID; check ABI to make sure that logged types are well-formed
Jan 05 13:02:07.890  WARN fuel_indexer::ffi: Unknown selector; check ABI to make sure function outputs match to types
Jan 05 13:02:07.890  WARN fuel_indexer::ffi: Unknown type ID; check ABI to make sure types are well-formed
Jan 05 13:02:07.890 ERROR fuel_indexer::executor: WasmIndexExecutor handle_events failed: unreachable.
Jan 05 13:02:07.892  INFO sqlx::query: ROLLBACK; rows affected: 0, rows returned: 0, elapsed: 2.203ms
Jan 05 13:02:07.893 ERROR fuel_indexer::service: Indexer executor failed RuntimeError(RuntimeError { source: Trap(UnreachableCodeReached), wasm_trace: [], native_trace:    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
 }), retrying.
```

### The bug

When a ReturnData receipt is processed, it expects the `return_types` vec to have at least one element, which is pushed onto each time there is a `Call` receipt: https://github.com/FuelLabs/fuel-indexer/blob/master/packages/fuel-indexer-macros/src/indexer.rs#L548

When I return a `u64` in my function, there is exactly 1 Call and exactly 1 ReturnData receipt, so this is fine. However when I return a `b256` in my function, there is exactly 1 Call but now 2 ReturnData receipts. This causes that `pop` for the second ReturnData to return None, and the `expect` panics.

I confirmed this was the issue by locally changing the ReturnData branch to be the following, which now works:
```
if let Some(selector) = return_types.pop() { // .expect("No return type available. <('-'<)");
  decoder.decode_return_type(selector, data);
}
```

Holding off on submitting a PR because I have a feeling this probably isn't the best permanent fix. In the case where I'm returning a u64, the ReturnData receipt doesn't actually correspond afaict to the Call that's made, so I also wonder if any decoding is necessary for a Return?
Generally I'm a bit spooked of the fragility of expecting certain receipts to exist following other receipts - is this a safe guarantee for 100% of txs or could a clever actor craft their own contract that would violate this expectation?

### PR DESCRIPTION
**Pull request by deekerno**
Closes #449 and #458.

## Changelog
- Adds `callees` HashSet to track contracts that actually need return type decoding
- Adds support for `Return` receipts

## Testing Plan
CI should pass. Also, spoke with @tkporter (who reported #449) and verified that this fix worked for them.

_Note: There was a bug in `fuels-rs` that was stripping out receipts in error; see https://github.com/FuelLabs/fuels-rs/pull/777. As such, there are no tests in our testing suite for `Return` decoding until we can upgrade._

### CODE REVIEW

File: packages/fuel-indexer-plugin/src/lib.rs [hunk 1]
```diff
@@ -24,4 +24,6 @@ pub mod prelude {
     pub use super::types::*;
 
     pub use super::utils::*;
+
+    pub use std::collections::HashSet;
```
Comment (ra0x3) [inline packages/fuel-indexer-plugin/src/lib.rs:28]: @deekerno 
- Plugin imports now happen usually in `fuel-indexer-plugin/src/wasm.rs` (for wasm) or `fuel-indexer-plugin/src/native.rs` (for native)
- But for this you can put it in the wasm macro module [here](https://github.com/FuelLabs/fuel-indexer/blob/master/packages/fuel-indexer-macros/src/wasm.rs#L39)
  - Or you can move both the `HashMap` and `HashSet` imports to the proper place `fuel-indexer-plugin/src/wasm.rs` (in this case)

File: packages/fuel-indexer-macros/src/indexer.rs [hunk 2]
```diff
@@ -537,16 +537,22 @@ fn process_fn_items(
...
+                            Receipt::Call { param1, id, to, ..} => {
                                 #contract_conditional
                                 return_types.push(param1);
+                                callees.insert(to);
                             }
                             Receipt::ReturnData { data, id, .. } => {
                                 #contract_conditional
-                                let selector = return_types.pop().expect("No return type available. <('-'<)");
-                                decoder.decode_return_type(selector, data);
+                                if callees.contains(&id) {
```
Comment (ra0x3) [inline packages/fuel-indexer-macros/src/indexer.rs:552]: @deekerno  
- I think this `callee` logic is fair. 
- Looking over the issue https://github.com/FuelLabs/fuel-indexer/issues/449 it looks like the `callee` logic works also with `Receipt::Return` in addition to `Receipt::ReturnData`
- Meaning, if we add `Receipt::Return` and have it look in the `callee` as well, I think this still fixes the bug, as well as addresses the case where you have a `Receipt::Return` and a `Receipt::ReturnData`, but only the `Receipt::Return` having a valid `id` param

Here's the example from the issue:
```
receipts: [
  Call { id: 0000000000000000000000000000000000000000000000000000000000000000, to: 69ec8b0544b6549354e373e021fc874305176c7b81db6da8d16cded3950d9f9f, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 99970291, param1: 4000556463, param2: 0, pc: 17216, is: 17216 },
  LogData { id: 69ec8b0544b6549354e373e021fc874305176c7b81db6da8d16cded3950d9f9f, ra: 0, rb: 6846832, ptr: 67108626, len: 77, digest: ccbcf7ee5796d9316fd3472b561feb99a51d3d97e82426b75df4a093faedc890, data: [0, 0, 0, 0, 0, 102, 117, 101, 108, 107, 99, 128, 76, 251, 249, 133, 110, 104, 229, 182, 231, 174, 242, 56, 220, 131, 17, 236, 85, 190, 192, 77, 247, 116, 0, 58, 44, 150, 224, 65, 142, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], pc: 25284, is: 17216 },
  Return { id: 69ec8b0544b6549354e373e021fc874305176c7b81db6da8d16cded3950d9f9f, val: 69, pc: 25292, is: 17216 },
  ReturnData { id: 0000000000000000000000000000000000000000000000000000000000000000, ptr: 67108544, len: 160, digest: de5c8876a60211bd60e33fed909e43cc8762a364833eb5c0014a745283045d78, data: [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 69, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 184, 0, 0, 0, 0, 0, 0, 58, 152, 0, 0, 0, 0, 0, 0, 64, 232, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 255, 255, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 245, 98, 243, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 104, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 245, 108, 243, 0, 0, 0, 0, 0, 0, 59, 240], pc: 11496, is: 10344 },
  ScriptResult { result: Success, gas_used: 135105 }], id: 371821733e4c23b30791fb078dd269b58e2481a3ec662a13ee1fc047fce62c5c }
]
```
- With your existing code, we would have pushed a `Receipt::Call`, but we wouldn't have popped anything because the `Receipt::ReturnData`'s `id` is invalid, but the `Receipt::Return`'s `id` _is_ valid

**Review by ra0x3 — CHANGES_REQUESTED** [review]
Small comments

File: packages/fuel-indexer-macros/src/indexer.rs (hunk 2 above)
Comment (deekerno) [reply packages/fuel-indexer-macros/src/indexer.rs:552]: That sounds good; I'm working on `Return` receipt support right now, so I'll ping you for a re-review once that's merged and this is adjusted.

File: packages/fuel-indexer-plugin/src/lib.rs (hunk 1 above)
Comment (deekerno) [reply packages/fuel-indexer-plugin/src/lib.rs:28]: Ah, I see. Sounds good to me. 👌🏽

File: packages/fuel-indexer-macros/src/indexer.rs (hunk 2 above)
Comment (ra0x3) [reply packages/fuel-indexer-macros/src/indexer.rs:552]: +1 for same PR

**Review by ra0x3 — APPROVED** [review]
Awesome stuff @deekerno 🚢
